version: "{build}"
shallow_clone: true

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  configuration: $(configuration)

init:
- cmd: msbuild /version /nologo
- cmd: dotnet --version

before_build:
- cmd: dotnet restore

build:
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\MassTransit.Extensions.Hosting.*.nupkg'
  name: Packages

deploy:
- provider: NuGet
  name: Release
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: pzvKbbudjmurey9no+lmNxd6Ns4zlxtA53dWSTIzjJO2VwKXzWScLTkjUK3s87YO
- provider: GitHub
  auth_token:
    secure: MSUVTCMCvD3SXQ6unyvSaBDi0uSd+hoE9bil07nvHeF68LOiw6vn04VnW8lo85JZ
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: "CI build of the latest master branch by Appveyor"
  artifact: Packages
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true
    tag: $(APPVEYOR_REPO_TAG_NAME)