image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- cmd: ECHO configuration=$(configuration)
- cmd: dotnet --version
- cmd: dotnet restore

build_script:
- cmd: dotnet build --configuration Release

artifacts:
- path: '**\MassTransit.Extensions.Hosting.*.nupkg'
