version: "{build}"
shallow_clone: true

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  configuration: $(configuration)

init:
- cmd: msbuild /version
- cmd: dotnet --version

before_build:
- cmd: dotnet restore

build:
  parallel: true
  verbosity: minimal

artifacts:
- path: '**\MassTransit.Extensions.Hosting.*.nupkg'
