image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  configuration: $(configuration)

before_build:
- cmd: dotnet --version
- cmd: dotnet restore

build:
  parallel: true
  verbosity: quiet

artifacts:
- path: '**\MassTransit.Extensions.Hosting.*.nupkg'
