image: Visual Studio 2017
configuration: Release
platform: Any CPU

cache:
- '%USERPROFILE%\.nuget\packages'
- '%LocalAppData%\NuGet\v3-cache'

before_build:
- cmd: dotnet restore

build_script:
- cmd: dotnet build --configuration $(configuration)

artifacts:
- path: '**\MassTransit.Extensions.Hosting.*.nupkg'
