image: Visual Studio 2017
configuration: Release
platform: Any CPU

cache:
- '%USERPROFILE%\.nuget\packages'
- '%LocalAppData%\NuGet\v3-cache'

before_build:
- cmd: dotnet --version
- cmd: dotnet restore

build:
  parallel: true
  verbosity: normal

artifacts:
- path: '**\MassTransit.Extensions.Hosting.*.nupkg'
