image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  configuration: $(configuration)

before_build:
- cmd: ECHO configuration1=%configuration%
- cmd: ECHO configuration2=$(configuration)
- cmd: dotnet --version
- cmd: dotnet restore

build_script:
- cmd: dotnet build --configuration Release

artifacts:
- path: '**\MassTransit.Extensions.Hosting.*.nupkg'
